import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    // Data for the SampleType table
    const sampleTypes = [
        { id: 1, name: 'Water and Wastewater' },
        { id: 2, name: 'Sediments' },
        { id: 3, name: 'Wastes' },
        { id: 4, name: 'Stationary Source Emissions' },
        { id: 5, name: 'Ambient Air' },
        { id: 6, name: 'Transformer Oil / Waste Oil' },
    ];

    const parameters = [
        { id:1, sampleTypeId: 1, name: 'Ammonia as NH₃-N' },
        { id:2, sampleTypeId: 1, name: 'Arsenic' },
        { id:3, sampleTypeId: 1, name: 'BTEX (Benzene, Toluene, Ethylbenzene, Xylene)' },
        { id:4, sampleTypeId: 1, name: 'Trichloroethylene' },
        { id:5, sampleTypeId: 1, name: 'BOD' },
        { id:6, sampleTypeId: 1, name: 'Boron' },
        { id:7, sampleTypeId: 1, name: 'Cadmium' },
        { id:8, sampleTypeId: 1, name: 'Iron' },
        { id:9, sampleTypeId: 1, name: 'Copper' },
        { id:10, sampleTypeId: 1, name: 'Lead' },
        { id:11, sampleTypeId: 1, name: 'Copper as Dissolved Copper' },
        { id:12, sampleTypeId: 1, name: 'Manganese' },
        { id:13, sampleTypeId: 1, name: 'Nickel' },
        { id:14, sampleTypeId: 1, name: 'Zinc' },
        { id:15, sampleTypeId: 1, name: 'Chemical Oxygen Demand' },
        { id:16, sampleTypeId: 1, name: 'Chloride' },
        { id:17, sampleTypeId: 1, name: 'Chromium as Hexavalent Chromium (Cr6+)' },
        { id:18, sampleTypeId: 1, name: 'Coliform, Fecal' },
        { id:19, sampleTypeId: 1, name: 'Coliform, Total' },
        { id:20, sampleTypeId: 1, name: 'Color (True)' },
        { id:21, sampleTypeId: 1, name: 'Color (Apparent)' },
        { id:22, sampleTypeId: 1, name: 'Cyanide as Free Cyanide' },
        { id:23, sampleTypeId: 1, name: 'Dissolved Oxygen' },
        { id:24, sampleTypeId: 1, name: 'Fluoride' },
        { id:25, sampleTypeId: 1, name: 'Malathion (Organophosphate)' },
        { id:26, sampleTypeId: 1, name: 'Mercury' },
        { id:27, sampleTypeId: 1, name: 'Nitrate as NO₃-N' },
        { id:28, sampleTypeId: 1, name: 'Oil and Grease' },
        { id:29, sampleTypeId: 1, name: 'Organochlorine Pesticides' },
        { id:30, sampleTypeId: 1, name: 'pH' },
        { id:31, sampleTypeId: 1, name: 'Phenol and Phenolic Substances' },
        { id:32, sampleTypeId: 1, name: 'Phosphate' },
        { id:33, sampleTypeId: 1, name: 'Polychlorinated Biphenyls' },
        { id:34, sampleTypeId: 1, name: 'Selenium' },
        { id:35, sampleTypeId: 1, name: 'Settleable Solids' },
        { id:36, sampleTypeId: 1, name: 'Sulfate' },
        { id:37, sampleTypeId: 1, name: 'Surfactants (Methylene Blue Active Substances)' },
        { id:38, sampleTypeId: 1, name: 'Temperature' },
        { id:39, sampleTypeId: 1, name: 'Total Dissolved Solids' },
        { id:40, sampleTypeId: 1, name: 'Total Suspended Solids' },
        { id:41, sampleTypeId: 2, name: 'Arsenic' },
        { id:42, sampleTypeId: 2, name: 'Cadmium, Total' },
        { id:43, sampleTypeId: 2, name: 'Copper' },
        { id:44, sampleTypeId: 2, name: 'Iron' },
        { id:45, sampleTypeId: 3, name: 'Arsenic and its compounds' },
        { id:46, sampleTypeId: 3, name: 'Barium and its compounds' },
        { id:47, sampleTypeId: 3, name: 'Cadmium and its compounds' },
        { id:48, sampleTypeId: 3, name: 'Chromium compounds' },
        { id:49, sampleTypeId: 3, name: 'Lead compounds' },
        { id:50, sampleTypeId: 3, name: 'Selenium and its compounds' },
        { id:51, sampleTypeId: 3, name: 'Silver and its compounds' },
        { id:52, sampleTypeId: 4, name: 'Antimony and its compounds' },
        { id:53, sampleTypeId: 4, name: 'Arsenic and its compounds' },
        { id:54, sampleTypeId: 4, name: 'Cadmium and its compounds' },
        { id:55, sampleTypeId: 4, name: 'Copper and its compounds' },
        { id:56, sampleTypeId: 4, name: 'Lead' },
        { id:57, sampleTypeId: 4, name: 'Nickel and its compounds Except Nickel Carbonyl' },
        { id:58, sampleTypeId: 4, name: 'Zinc and its compounds' },
        { id:59, sampleTypeId: 2, name: 'Lead' },
        { id:60, sampleTypeId: 2, name: 'Manganese' },
        { id:61, sampleTypeId: 2, name: 'Nickel' },
        { id:62, sampleTypeId: 2, name: 'Silver' },
        { id:63, sampleTypeId: 2, name: 'Zinc' },
        { id:64, sampleTypeId: 4, name: 'Hydrogen Sulfide' },
        { id:65, sampleTypeId: 5, name: 'Nitrogen Dioxide' },
        { id:66, sampleTypeId: 5, name: 'Ozone' },
        { id:67, sampleTypeId: 2, name: 'Mercury, Total' },
        { id:68, sampleTypeId: 1, name: 'Mercury and Mercury compounds' },
        { id:69, sampleTypeId: 4, name: 'Mercury' },
        { id:70, sampleTypeId: 1, name: 'Barium' },
        { id:71, sampleTypeId: 3, name: 'pH / Corrosivity' },
        { id:72, sampleTypeId: 5, name: 'Sulfur Dioxide' },
        { id:73, sampleTypeId: 2, name: 'Organochlorine Pesticides (OCPs)' },
        { id:74, sampleTypeId: 2, name: 'Polychlorinated Biphenyls (PCBs)' },
        { id:75, sampleTypeId: 2, name: 'Organophosphate Pesticides' },
        { id:76, sampleTypeId: 6, name: 'Polychlorinated Biphenyls (PCBs)' },
        { id:77, sampleTypeId: 1, name: 'Benzo(a)pyrene' },
        { id:78, sampleTypeId: 5, name: 'Suspended Particulate Matter - PM2.5' },
        { id:79, sampleTypeId: 4, name: 'Particulates' },
        { id:80, sampleTypeId: 5, name: 'Suspended Particulate Matter - TSP' },
        { id:81, sampleTypeId: 5, name: 'Lead' },
        { id:82, sampleTypeId: 5, name: 'Cadmium' },
        { id:83, sampleTypeId: 5, name: 'Suspended Particulate Matter - PM10' },
        { id:84, sampleTypeId: 5, name: 'Ammonia' },
        { id:85, sampleTypeId: 3, name: 'Fluoride and its compounds' },
        { id:86, sampleTypeId: 5, name: 'Chlorine and Chlorine compounds' },
        { id:87, sampleTypeId: 5, name: 'Hydrogen Sulfide' },
        { id:88, sampleTypeId: 4, name: 'Carbon Monoxide' },
        { id:89, sampleTypeId: 5, name: 'Carbon Monoxide' },
        { id:90, sampleTypeId: 4, name: 'NOx' },
        { id:91, sampleTypeId: 4, name: 'Sulfur Oxides as SO₂' },
        { id:92, sampleTypeId: 4, name: 'Hydrofluoric Acid and Fluoride compounds' },
        { id:93, sampleTypeId: 5, name: 'Antimony' },
        { id:94, sampleTypeId: 5, name: 'Arsenic' },
        { id:95, sampleTypeId: 3, name: 'Copper and its compounds' },
        { id:96, sampleTypeId: 3, name: 'Hexavalent Chromium compounds' },
        { id:97, sampleTypeId: 3, name: 'Mercury and Mercury compounds' },
        { id:98, sampleTypeId: 3, name: 'Zinc and its compound' },
        { id:99, sampleTypeId: 2, name: 'Total Coliform' },
        { id:100, sampleTypeId: 2, name: 'Fecal Coliform' },
        { id:101, sampleTypeId: 4, name: 'Cobalt and its compounds' },
        { id:102, sampleTypeId: 1, name: 'Phenols' },
        { id:103, sampleTypeId: 4, name: 'Chromium and its compounds' },
        { id:104, sampleTypeId: 4, name: 'Manganese and its compounds' },
        { id:105, sampleTypeId: 4, name: 'Phosphorus Pentoxide' },
        { id:106, sampleTypeId: 4, name: 'Thallium and its compounds' },
        { id:107, sampleTypeId: 4, name: 'Vanadium and its compounds' },
        { id:108, sampleTypeId: 3, name: 'Antimony and its compounds' },
        { id:109, sampleTypeId: 3, name: 'Beryllium and its compounds' },
        { id:110, sampleTypeId: 3, name: 'Thallium and its compounds' },
        { id:111, sampleTypeId: 1, name: 'Copper Total' },
    ];


    const sampleMethods = [
        { id: 1, parameterId: 1, name: 'Ammonia – Selective Electrode Method' },
        { id: 2, parameterId: 1, name: 'Phenate Method' },
        { id: 3, parameterId: 1, name: 'Automated Phenate Method' },
        { id: 4, parameterId: 2, name: 'Silver Diethyldithiocarbamate Method' },
        { id: 5, parameterId: 41, name: 'Manual Hydride Generation / Atomic Absorption Spectrophotometric Method' },
        { id: 6, parameterId: 42, name: 'Atomic Absorption Spectrophotometric Method (Wet Ashing)' },
        { id: 7, parameterId: 43, name: 'Atomic Absorption Spectrophotometric Method (Wet Ashing)' },
        { id: 8, parameterId: 44, name: 'Atomic Absorption Spectrophotometric Method (Wet Ashing)' },
        { id: 9, parameterId: 5, name: '5-Day BOD Test' },
        { id: 10, parameterId: 5, name: 'Sample' },
        { id: 11, parameterId: 45, name: 'AAS (US EPA Method 1311)' },
        { id: 12, parameterId: 46, name: 'AAS (US EPA Method 1311)' },
        { id: 13, parameterId: 36, name: 'Automated Methylthymol Blue Method' },
        { id: 14, parameterId: 47, name: 'AAS (US EPA Method 1311)' },
        { id: 15, parameterId: 48, name: 'AAS (US EPA Method 1311)' },
        { id: 16, parameterId: 49, name: 'AAS (US EPA Method 1311)' },
        { id: 17, parameterId: 50, name: 'AAS (US EPA Method 1311)' },
        { id: 18, parameterId: 51, name: 'AAS (US EPA Method 1311)' },
        { id: 19, parameterId: 52, name: 'AAS (US EPA Method 29)' },
        { id: 20, parameterId: 53, name: 'AAS (US EPA Method 29)' },
        { id: 21, parameterId: 54, name: 'AAS (US EPA Method 29)' },
        { id: 22, parameterId: 55, name: 'AAS (US EPA Method 29)' },
        { id: 23, parameterId: 56, name: 'AAS (US EPA Method 29)' },
        { id: 24, parameterId: 57, name: 'AAS (US EPA Method 29)' },
        { id: 25, parameterId: 58, name: 'AAS (US EPA Method 29)' },
        { id: 26, parameterId: 37, name: 'Anionic Surfactants as MBAS' },
        { id: 27, parameterId: 16, name: 'Argentometric Method' },
        { id: 28, parameterId: 32, name: 'Ascorbic Acid Method' },
        { id: 29, parameterId: 59, name: 'Atomic Absorption Spectrophotometric Method (Wet Ashing)' },
        { id: 30, parameterId: 60, name: 'Atomic Absorption Spectrophotometric Method (Wet Ashing)' },
        { id: 31, parameterId: 61, name: 'Atomic Absorption Spectrophotometric Method (Wet Ashing)' },
        { id: 32, parameterId: 62, name: 'Atomic Absorption Spectrophotometric Method (Wet Ashing)' },
        { id: 33, parameterId: 63, name: 'Atomic Absorption Spectrophotometric Method (Wet Ashing)' },
        { id: 34, parameterId: 32, name: 'Automated Ascorbic Acid Reduction Method' },
        { id: 35, parameterId: 27, name: 'Cadmium Reduction Method with Nitrite correction using Colorimetric Method' },
        { id: 36, parameterId: 64, name: 'Cadmium Sulfide Method' },
        { id: 37, parameterId: 6, name: 'Carmine Method' },
        { id: 38, parameterId: 65, name: 'Chemiluminescence Method' },
        { id: 39, parameterId: 66, name: 'Chemiluminescence Method' },
        { id: 40, parameterId: 15, name: 'Closed Reflux, Colorimetric Method' },
        { id: 41, parameterId: 15, name: 'Closed Reflux, Titrimetric Method' },
        { id: 42, parameterId: 67, name: 'Cold - Vapor Atomic Absorption Spectrophotometric Method' },
        { id: 43, parameterId: 26, name: 'Cold – Vapor Atomic Absorption Spectrophotometric Method' },
        { id: 44, parameterId: 26, name: 'Cold – Vapor Atomic Fluorescence Spectrometry' },
        { id: 45, parameterId: 68, name: 'Cold Vapor AAS Method (US EPA Method 1311)' },
        { id: 46, parameterId: 17, name: 'Colorimetric Method' },
        { id: 47, parameterId: 27, name: 'Colorimetric, Brucine' },
        { id: 48, parameterId: 6, name: 'Curcumin Method' },
        { id: 49, parameterId: 69, name: 'CVAAS (US EPA Method 29)' },
        { id: 50, parameterId: 22, name: 'Cyanide – Selective Electrode (w/o distillation)' },
        { id: 51, parameterId: 7, name: 'Direct Air-Acetylene Flame Method (Nitric Acid - Hydrochloric Acid/  Hotplate Digestion)' },
        { id: 52, parameterId: 7, name: 'Direct Air-Acetylene Flame Method (Microwave – Assisted Digestion)' },
        { id: 53, parameterId: 9, name: 'Direct Air-Acetylene Flame Method (Nitric Acid - Hydrochloric Acid/  Hotplate Digestion)' },
        { id: 54, parameterId: 9, name: 'Direct Air-Acetylene Flame Method (Microwave – Assisted Digestion)' },
        { id: 55, parameterId: 11, name: 'Direct Air-Acetylene Flame Method (Nitric Acid - Hydrochloric Acid/  Hotplate Digestion)' },
        { id: 56, parameterId: 11, name: 'Direct Air-Acetylene Flame Method (Microwave – Assisted Digestion)' },
        { id: 57, parameterId: 8, name: 'Direct Air-Acetylene Flame Method (Nitric Acid - Hydrochloric Acid/  Hotplate Digestion)' },
        { id: 58, parameterId: 8, name: 'Direct Air-Acetylene Flame Method (Microwave – Assisted Digestion)' },
        { id: 59, parameterId: 12, name: 'Direct Air-Acetylene Flame Method (Nitric Acid - Hydrochloric Acid/  Hotplate Digestion)' },
        { id: 60, parameterId: 12, name: 'Direct Air-Acetylene Flame Method (Microwave – Assisted Digestion)' },
        { id: 61, parameterId: 13, name: 'Direct Air-Acetylene Flame Method (Nitric Acid - Hydrochloric Acid/  Hotplate Digestion)' },
        { id: 62, parameterId: 13, name: 'Direct Air-Acetylene Flame Method (Microwave – Assisted Digestion)' },
        { id: 63, parameterId: 14, name: 'Direct Air-Acetylene Flame Method (Nitric Acid - Hydrochloric Acid/  Hotplate Digestion)' },
        { id: 64, parameterId: 14, name: 'Direct Air-Acetylene Flame Method (Microwave – Assisted Digestion)' },
        { id: 65, parameterId: 10, name: 'Direct Air-Acetylene Flame Method (Nitric Acid/  Hotplate Digestion)' },
        { id: 66, parameterId: 10, name: 'Direct Air-Acetylene Flame Method (Microwave – Assisted Digestion)' },
        { id: 67, parameterId: 70, name: 'Direct Nitrous Oxide-Acetylene Flame Method (Microwave – Assisted Digestion)' },
        { id: 68, parameterId: 70, name: 'Direct Nitrous Oxide-Acetylene Flame Method (Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 69, parameterId: 71, name: 'Electrometric Method' },
        { id: 70, parameterId: 30, name: 'Electrometric Method' },
        { id: 71, parameterId: 2, name: 'Electrothermal Atomic Absorption Spectrometric Method (Microwave – Assisted Digestion)' },
        { id: 72, parameterId: 70, name: 'Electrothermal Atomic Absorption Spectrometric Method (Microwave – Assisted Digestion)' },
        { id: 73, parameterId: 7, name: 'Electrothermal Atomic Absorption Spectrometric Method (Microwave – Assisted Digestion)' },
        { id: 74, parameterId: 9, name: 'Electrothermal Atomic Absorption Spectrometric Method (Microwave – Assisted Digestion)' },
        { id: 75, parameterId: 11, name: 'Electrothermal Atomic Absorption Spectrometric Method (Microwave – Assisted Digestion)' },
        { id: 76, parameterId: 8, name: 'Electrothermal Atomic Absorption Spectrometric Method (Microwave – Assisted Digestion)' },
        { id: 77, parameterId: 10, name: 'Electrothermal Atomic Absorption Spectrometric Method (Microwave – Assisted Digestion)' },
        { id: 78, parameterId: 12, name: 'Electrothermal Atomic Absorption Spectrometric Method (Microwave – Assisted Digestion)' },
        { id: 79, parameterId: 13, name: 'Electrothermal Atomic Absorption Spectrometric Method (Microwave – Assisted Digestion)' },
        { id: 80, parameterId: 34, name: 'Electrothermal Atomic Absorption Spectrometric Method (Microwave – Assisted Digestion)' },
        { id: 81, parameterId: 19, name: 'Enzyme Substrate Test' },
        { id: 82, parameterId: 3, name: 'Equilibrium Headspace Analysis/Capillary-Column Gas Chromatographic Method' },
        { id: 83, parameterId: 4, name: 'Equilibrium Headspace Analysis/ Capillary-Column Gas Chromatographic Method' },
        { id: 84, parameterId: 7, name: 'Extraction/Air-Acetylene Flame Method' },
        { id: 85, parameterId: 9, name: 'Extraction/Air-Acetylene Flame Method' },
        { id: 86, parameterId: 11, name: 'Extraction/Air-Acetylene Flame Method' },
        { id: 87, parameterId: 8, name: 'Extraction/Air-Acetylene Flame Method' },
        { id: 88, parameterId: 10, name: 'Extraction/Air-Acetylene Flame Method' },
        { id: 89, parameterId: 12, name: 'Extraction/Air-Acetylene Flame Method' },
        { id: 90, parameterId: 13, name: 'Extraction/Air-Acetylene Flame Method' },
        { id: 91, parameterId: 14, name: 'Extraction/Air-Acetylene Flame Method' },
        { id: 92, parameterId: 70, name: 'Extraction/Nitrous-Oxide – Acetylene Flame Method' },
        { id: 93, parameterId: 65, name: 'Gas Bubbler Griess-Saltzman' },
        { id: 94, parameterId: 29, name: 'Gas Chromatographic / Electron Capture Detector Method' },
        { id: 95, parameterId: 33, name: 'Gas Chromatographic / Electron Capture Detector Method' },
        { id: 96, parameterId: 25, name: 'Gas Chromatographic / Flame Photometric Detector' },
        { id: 97, parameterId: 25, name: 'Gas Chromatographic / Mass Spectrometric Method' },
        { id: 98, parameterId: 29, name: 'Gas Chromatographic / Mass Spectrometric Method' },
        { id: 99, parameterId: 33, name: 'Gas Chromatographic / Mass Spectrometric Method' },
        { id: 100, parameterId: 31, name: 'Gas Chromatographic Method' },
        { id: 101, parameterId: 73, name: 'Gas Chromatographic Method (Electron Capture Detector)' },
        { id: 102, parameterId: 74, name: 'Gas Chromatographic Method (Electron Capture Detector)' },
        { id: 103, parameterId: 75, name: 'Gas Chromatographic Method (Flame Photometric Detector)' },
        { id: 104, parameterId: 76, name: 'Gas Chromatographic Method / Electron Capture Detector' },
        { id: 105, parameterId: 77, name: 'Gas Chromatographic/ Flame Ionization Detector Method' },
        { id: 106, parameterId: 77, name: 'Gas Chromatographic/ Mass Spectrometric Method' },
        { id: 107, parameterId: 31, name: 'Gas Chromatographic/ Mass Spectrometric Method' },
        { id: 108, parameterId: 52, name: 'GFAAS (US EPA Method 29)' },
        { id: 109, parameterId: 53, name: 'GFAAS (US EPA Method 29)' },
        { id: 110, parameterId: 54, name: 'GFAAS (US EPA Method 29)' },
        { id: 111, parameterId: 56, name: 'GFAAS (US EPA Method 29)' },
        { id: 112, parameterId: 78, name: 'Gravimetric Method' },
        { id: 113, parameterId: 79, name: 'Gravimetric Method' },
        { id: 114, parameterId: 40, name: 'Gravimetric, Dried at 103-105°C' },
        { id: 115, parameterId: 39, name: 'Gravimetric, Dried at 180°C' },
        { id: 116, parameterId: 77, name: 'High Performance Liquid Chromatographic Method' },
        { id: 117, parameterId: 80, name: 'High Volume - Gravimetric' },
        { id: 118, parameterId: 81, name: 'High Volume and Atomic Absorption Spectrophotometry' },
        { id: 119, parameterId: 82, name: 'High Volume Sampler and Atomic Absorption Spectrophotometric Method' },
        { id: 120, parameterId: 83, name: 'High Volume with 10 micron particle-size inlet; Gravimetric' },
        { id: 121, parameterId: 52, name: 'ICP-MS (US EPA Method 29)' },
        { id: 122, parameterId: 53, name: 'ICP-MS (US EPA Method 29)' },
        { id: 123, parameterId: 54, name: 'ICP-MS (US EPA Method 29)' },
        { id: 124, parameterId: 55, name: 'ICP-MS (US EPA Method 29)' },
        { id: 125, parameterId: 56, name: 'ICP-MS (US EPA Method 29)' },
        { id: 126, parameterId: 57, name: 'ICP-MS (US EPA Method 29)' },
        { id: 127, parameterId: 58, name: 'ICP-MS (US EPA Method 29)' },
        { id: 128, parameterId: 53, name: 'ICP-OES (US EPA Method 1311)' },
        { id: 129, parameterId: 45, name: 'ICP-OES (US EPA Method 1311)' },
        { id: 130, parameterId: 46, name: 'ICP-OES (US EPA Method 1311)' },
        { id: 131, parameterId: 47, name: 'ICP-OES (US EPA Method 1311)' },
        { id: 132, parameterId: 48, name: 'ICP-OES (US EPA Method 1311)' },
        { id: 133, parameterId: 49, name: 'ICP-OES (US EPA Method 1311)' },
        { id: 134, parameterId: 50, name: 'ICP-OES (US EPA Method 1311)' },
        { id: 135, parameterId: 51, name: 'ICP-OES (US EPA Method 1311)' },
        { id: 136, parameterId: 52, name: 'ICP-OES (US EPA Method 29)' },
        { id: 137, parameterId: 53, name: 'ICP-OES (US EPA Method 29)' },
        { id: 138, parameterId: 54, name: 'ICP-OES (US EPA Method 29)' },
        { id: 139, parameterId: 55, name: 'ICP-OES (US EPA Method 29)' },
        { id: 140, parameterId: 56, name: 'ICP-OES (US EPA Method 29)' },
        { id: 141, parameterId: 57, name: 'ICP-OES (US EPA Method 29)' },
        { id: 142, parameterId: 58, name: 'ICP-OES (US EPA Method 29)' },
        { id: 143, parameterId: 35, name: 'Imhoff Cone Method' },
        { id: 144, parameterId: 84, name: 'Indophenol Method' },
        { id: 145, parameterId: 41, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Wet Ashing)' },
        { id: 146, parameterId: 42, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Wet Ashing)' },
        { id: 147, parameterId: 43, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Wet Ashing)' },
        { id: 148, parameterId: 44, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Wet Ashing)' },
        { id: 149, parameterId: 59, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Wet Ashing)' },
        { id: 150, parameterId: 60, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Wet Ashing)' },
        { id: 151, parameterId: 61, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Wet Ashing)' },
        { id: 152, parameterId: 62, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Wet Ashing)' },
        { id: 153, parameterId: 63, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Wet Ashing)' },
        { id: 154, parameterId: 34, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method(Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 155, parameterId: 7, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method(Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 156, parameterId: 9, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method(Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 157, parameterId: 11, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 158, parameterId: 11, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method(Microwave - Assisted Digestion)' },
        { id: 159, parameterId: 8, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method(Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 160, parameterId: 10, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method(Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 161, parameterId: 12, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method(Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 162, parameterId: 13, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method(Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 163, parameterId: 14, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method(Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 164, parameterId: 2, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Microwave – Assisted Digestion)' },
        { id: 165, parameterId: 70, name: 'Inductively Coupled Plasma - Mass Spectrometry Method(Microwave – Assisted Digestion)' },
        { id: 166, parameterId: 34, name: 'Inductively Coupled Plasma - Mass Spectrometry Method(Nitric Acid / Hotplate Digestion)' },
        { id: 167, parameterId: 6, name: 'Inductively Coupled Plasma - Mass Spectrometry Method(Nitric Acid / Hotplate Digestion) Inductively Coupled Plasma - Mass Spectrometry Method(Nitric Acid / Hotplate Digestion)' },
        { id: 168, parameterId: 7, name: 'Inductively Coupled Plasma - Mass Spectrometry Method(Nitric Acid / Hotplate Digestion)' },
        { id: 169, parameterId: 9, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Nitric Acid / Hotplate Digestion)' },
        { id: 170, parameterId: 11, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Nitric Acid / Hotplate Digestion)' },
        { id: 171, parameterId: 11, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Microwave – Assisted Digestion)' },
        { id: 172, parameterId: 34, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Microwave – Assisted Digestion)' },
        { id: 173, parameterId: 7, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Microwave – Assisted Digestion)' },
        { id: 174, parameterId: 9, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Microwave – Assisted Digestion)' },
        { id: 175, parameterId: 8, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Microwave – Assisted Digestion)' },
        { id: 176, parameterId: 10, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Microwave – Assisted Digestion)' },
        { id: 177, parameterId: 12, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Microwave – Assisted Digestion)' },
        { id: 178, parameterId: 13, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Microwave – Assisted Digestion)' },
        { id: 179, parameterId: 14, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Microwave – Assisted Digestion)' },
        { id: 180, parameterId: 2, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Nitric Acid / Hotplate Digestion)' },
        { id: 181, parameterId: 70, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Nitric Acid / Hotplate Digestion)' },
        { id: 182, parameterId: 34, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Microwave – Assisted Digestion)' },
        { id: 183, parameterId: 6, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Microwave – Assisted Digestion)' },
        { id: 184, parameterId: 7, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Microwave – Assisted Digestion)' },
        { id: 185, parameterId: 9, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Microwave – Assisted Digestion)' },
        { id: 186, parameterId: 8, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Nitric Acid / Hotplate Digestion)' },
        { id: 187, parameterId: 8, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Microwave – Assisted Digestion)' },
        { id: 188, parameterId: 10, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Nitric Acid / Hotplate Digestion)' },
        { id: 189, parameterId: 10, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Microwave – Assisted Digestion)' },
        { id: 190, parameterId: 12, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Nitric Acid / Hotplate Digestion)' },
        { id: 191, parameterId: 12, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Microwave – Assisted Digestion)' },
        { id: 192, parameterId: 13, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Nitric Acid / Hotplate Digestion)' },
        { id: 193, parameterId: 13, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Microwave – Assisted Digestion)' },
        { id: 194, parameterId: 14, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Nitric Acid / Hotplate Digestion)' },
        { id: 195, parameterId: 14, name: 'Inductively Coupled Plasma - Mass Spectrometry Method (Microwave – Assisted Digestion)' },
        { id: 196, parameterId: 2, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Microwave – Assisted Digestion)' },
        { id: 197, parameterId: 2, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 198, parameterId: 70, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Microwave – Assisted Digestion)' },
        { id: 199, parameterId: 70, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 200, parameterId: 6, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Nitric Acid - Hydrochloric Acid/ Hotplate Digestion)' },
        { id: 201, parameterId: 6, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Microwave – Assisted Digestion)' },
        { id: 202, parameterId: 23, name: 'Iodometric Method - Alum Flocculation Modification' },
        { id: 203, parameterId: 23, name: 'Iodometric Method - Azide Modification' },
        { id: 204, parameterId: 23, name: 'Iodometric Method - Copper Sulfate-Sulfamic Acid Flocculation Modification' },
        { id: 205, parameterId: 23, name: 'Iodometric Method - Permanganate Modification' },
        { id: 206, parameterId: 16, name: 'Ion Chromatography with Chemical Suppression of Eluent Conductivity' },
        { id: 207, parameterId: 24, name: 'Ion Chromatography with Chemical Suppression of Eluent Conductivity' },
        { id: 208, parameterId: 27, name: 'Ion Chromatography with Chemical Suppression of Eluent Conductivity' },
        { id: 209, parameterId: 36, name: 'Ion Chromatography with Chemical Suppression of Eluent Conductivity' },
        { id: 210, parameterId: 85, name: 'Ion Selective Electrode Method' },
        { id: 211, parameterId: 24, name: 'Ion-Selective Electrode Method' },
        { id: 212, parameterId: 38, name: 'Laboratory and Field Methods' },
        { id: 213, parameterId: 28, name: 'Liquid-Liquid, Partition - Gravimetric Method' },
        { id: 214, parameterId: 2, name: 'Manual Hydride Generation/ Atomic Absorption Spectrometric Method' },
        { id: 215, parameterId: 2, name: 'Manual Hydride Generation/ Atomic Absorption Spectrometric Method' },
        { id: 216, parameterId: 34, name: 'Manual Hydride Generation/ Atomic Absorption Spectrometric Method' },
        { id: 217, parameterId: 23, name: 'Membrane Electrode Method' },
        { id: 218, parameterId: 86, name: 'Methyl Orange Method' },
        { id: 219, parameterId: 87, name: 'Methylene Blue Method' },
        { id: 220, parameterId: 18, name: 'Multiple Tube Fermentation Technique – Fecal Coliform Procedure' },
        { id: 221, parameterId: 19, name: 'Multiple Tube Fermentation Technique – Standard Total Coliform Fermentation Technique' },
        { id: 222, parameterId: 88, name: 'NDIR' },
        { id: 223, parameterId: 66, name: 'Neutral Buffer Potassium Iodide (NBKI)' },
        { id: 224, parameterId: 27, name: 'Nitrate Electrode Method' },
        { id: 225, parameterId: 89, name: 'Non-dispersive Infra-red Spectrophotometry (NDIR)' },
        { id: 226, parameterId: 15, name: 'Open Reflux Method' },
        { id: 227, parameterId: 90, name: 'Phenol-disulfonicacid Method' },
        { id: 228, parameterId: 16, name: 'Potentiometric Method' },
        { id: 229, parameterId: 3, name: 'Purge and Trap Capillary-Column Gas Chromatographic Method' },
        { id: 230, parameterId: 4, name: 'Purge and Trap Capillary-Column Gas Chromatographic Method' },
        { id: 231, parameterId: 3, name: 'Purge and Trap Capillary-Column Gas Chromatographic/ Mass Spectrometric Method' },
        { id: 232, parameterId: 4, name: 'Purge and Trap Capillary-Column Gas Chromatographic/ Mass Spectrometric Method' },
        { id: 233, parameterId: 28, name: 'Solid – Phase, Partition Gravimetric Method' },
        { id: 234, parameterId: 85, name: 'SPADNS – Colorimetric Method' },
        { id: 235, parameterId: 24, name: 'SPADNS Method' },
        { id: 236, parameterId: 32, name: 'Stannous Chloride Method' },
        { id: 237, parameterId: 91, name: 'Titration Method with Barium Chloride using Thorin as indicator' },
        { id: 238, parameterId: 36, name: 'Turbidimetric Method' },
        { id: 239, parameterId: 92, name: 'US EPA Method 13' },
        { id: 240, parameterId: 92, name: 'US EPA Method 14' },
        { id: 241, parameterId: 32, name: 'Vanadomolybdophosphoric Acid Colorimetric Method' },
        { id: 242, parameterId: 21, name: 'Visual Comparison Method' },
        { id: 243, parameterId: 20, name: 'Visual Comparison Method' },
        { id: 244, parameterId: 101, name: 'USEPA method 29' },
        { id: 245, parameterId: 102, name: 'Chloroform Extraction Method' },
        { id: 246, parameterId: 103, name: 'USEPA Method 29' },
        { id: 247, parameterId: 104, name: 'USEPA Method 29' },
        { id: 248, parameterId: 105, name: 'USEPA Method 29 Colorimetry (Vanadomolybdophosphoric Acid)' },
        { id: 249, parameterId: 106, name: 'USEPA Method 29' },
        { id: 250, parameterId: 107, name: 'USEPA Method 29' },
        { id: 251, parameterId: 108, name: 'USEPA Method 1311/ICP-OES Method' },
        { id: 252, parameterId: 109, name: 'USEPA Method 1311/ICP-OES Method' },
        { id: 253, parameterId: 110, name: 'USEPA Method 1311/ICP-OES Method' },
        { id: 254, parameterId: 98, name: 'USEPA Method 1311/ICP-OES Method' },
        { id: 255, parameterId: 111, name: 'Direct Air - Acetylene Flame Method (Nitric Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 256, parameterId: 111, name: 'Inductively Coupled Plasma - Emission Spectroscopy Method (Nitric  Acid - Hydrochloric Acid / Hotplate Digestion)' },
        { id: 257, parameterId: 95, name: 'ICP-OES Method / USEPA Method 1311' },
        { id: 258, parameterId: 97, name: 'Cold Vapor AAS Method / USEPA Method 1311' },
        { id: 259, parameterId: 19, name: 'Multiple Tube Fermentation Technique – Standard Total Coliform Fermentation Technique' },
    ];


    const sampleReferences = [
        { id: 7 , sampleMethodId: 1 , name: 'SMEWW 4500-NH3 D' },
        { id: 8 , sampleMethodId: 3 , name: 'SMEWW 4500-NH₃ G' },
        { id: 9 , sampleMethodId: 2 , name: 'SMEWW 4500-NH₃ F' },
        { id: 10 , sampleMethodId: 4 , name: 'SMEWW 3500-As B' },
        { id: 13 , sampleMethodId: 13 , name: 'SMEWW 4500-SO₄²- F' },
        { id: 14 , sampleMethodId: 9 , name: 'SMEWW 5210 B' },
        { id: 15 , sampleMethodId: 26 , name: 'SMEWW 5540 C' },
        { id: 16 , sampleMethodId: 27 , name: 'SMEWW 4500-Cl- B' },
        { id: 17 , sampleMethodId: 28 , name: 'SMEWW 4500-P E' },
        { id: 18 , sampleMethodId: 34 , name: 'SMEWW 4500-P F' },
        { id: 19 , sampleMethodId: 35 , name: 'SMEWW 4500-NO₃ -E' },
        { id: 20 , sampleMethodId: 35 , name: 'SMEWW 4500-NO₂ -B' },
        { id: 21 , sampleMethodId: 37 , name: 'SMEWW 4500-B C' },
        { id: 22 , sampleMethodId: 40 , name: 'SMEWW 5220 D' },
        { id: 23 , sampleMethodId: 41 , name: 'SMEWW 5220 C' },
        { id: 24 , sampleMethodId: 43 , name: 'SMEWW 3112 B/ US EPA 7470' },
        { id: 25 , sampleMethodId: 44 , name: 'US EPA 245.7' },
        { id: 26 , sampleMethodId: 46 , name: 'SMEWW 3500-Cr B' },
        { id: 27 , sampleMethodId: 47 , name: 'US EPA 352.1' },
        { id: 28 , sampleMethodId: 48 , name: 'SMEWW 4500-B B' },
        { id: 29 , sampleMethodId: 50 , name: 'SMEWW 4500-CN- F/ US EPA 9213' },
        { id: 30 , sampleMethodId: 51 , name: 'SMEWW 3111 B (SMEWW 3030 F/ US EPA 3010)' },
        { id: 31 , sampleMethodId: 52 , name: 'SMEWW 3111 B  (SMEWW 3030 K / US EPA 3015)' },
        { id: 32 , sampleMethodId: 53 , name: 'SMEWW 3111 B (SMEWW 3030 F/ US EPA 3010)' },
        { id: 33 , sampleMethodId: 54 , name: 'SMEWW 3111 B  (SMEWW 3030 K / US EPA 3015)' },
        { id: 34 , sampleMethodId: 55 , name: 'SMEWW 3111 B (SMEWW 3030 F/ US EPA 3010)' },
        { id: 35 , sampleMethodId: 56 , name: 'SMEWW 3111 B  (SMEWW 3030 K / US EPA 3015)' },
        { id: 36 , sampleMethodId: 57 , name: 'SMEWW 3111 B (SMEWW 3030 F/ US EPA 3010)' },
        { id: 37 , sampleMethodId: 58 , name: 'SMEWW 3111 B  (SMEWW 3030 K / US EPA 3015)' },
        { id: 38 , sampleMethodId: 59 , name: 'SMEWW 3111 B (SMEWW 3030 F/ US EPA 3010)' },
        { id: 39 , sampleMethodId: 60 , name: 'SMEWW 3111 B  (SMEWW 3030 K / US EPA 3015)' },
        { id: 40 , sampleMethodId: 61 , name: 'SMEWW 3111 B (SMEWW 3030 F/ US EPA 3010)' },
        { id: 41 , sampleMethodId: 62 , name: 'SMEWW 3111 B  (SMEWW 3030 K / US EPA 3015)' },
        { id: 42 , sampleMethodId: 63 , name: 'SMEWW 3111 B (SMEWW 3030 F/ US EPA 3010)' },
        { id: 43 , sampleMethodId: 64 , name: 'SMEWW 3111 B  (SMEWW 3030 K / US EPA 3015)' },
        { id: 44 , sampleMethodId: 65 , name: 'SMEWW 3111 B (SMEWW 3030 E)' },
        { id: 45 , sampleMethodId: 66 , name: 'SMEWW 3111 B  (SMEWW 3030 K / US EPA 3015)' },
        { id: 46 , sampleMethodId: 67 , name: 'SMEWW 3111 D  (SMEWW 3030 K / USEPA 3015)' },
        { id: 47 , sampleMethodId: 68 , name: 'SMEWW 3111 D (SMEWW 3030 F/  USEPA 3010)' },
        { id: 48 , sampleMethodId: 70 , name: 'SMEWW 4500 - H⁺ B' },
        { id: 49 , sampleMethodId: 71 , name: 'SMEWW 3113  (SMEWW 3030 K/ US EPA 3015)' },
        { id: 50 , sampleMethodId: 71 , name: 'SMEWW 3113 (SMEWW 3030 E)' },
        { id: 51 , sampleMethodId: 72 , name: 'SMEWW 3113  (SMEWW 3030 K/ US EPA 3015)' },
        { id: 52 , sampleMethodId: 72 , name: 'SMEWW 3113 (SMEWW 3030 E)' },
        { id: 53 , sampleMethodId: 73 , name: 'SMEWW 3113  (SMEWW 3030 K/ US EPA 3015)' },
        { id: 54 , sampleMethodId: 73 , name: 'SMEWW 3113 (SMEWW 3030 E)' },
        { id: 55 , sampleMethodId: 74 , name: 'SMEWW 3113  (SMEWW 3030 K/ US EPA 3015)' },
        { id: 56 , sampleMethodId: 74 , name: 'SMEWW 3113 (SMEWW 3030 E)' },
        { id: 57 , sampleMethodId: 75 , name: 'SMEWW 3113  (SMEWW 3030 K/ US EPA 3015)' },
        { id: 58 , sampleMethodId: 75 , name: 'SMEWW 3113 (SMEWW 3030 E)' },
        { id: 59 , sampleMethodId: 76 , name: 'SMEWW 3113  (SMEWW 3030 K/ US EPA 3015)' },
        { id: 60 , sampleMethodId: 76 , name: 'SMEWW 3113 (SMEWW 3030 E)' },
        { id: 61 , sampleMethodId: 77 , name: 'SMEWW 3113  (SMEWW 3030 K/ US EPA 3015)' },
        { id: 62 , sampleMethodId: 77 , name: 'SMEWW 3113 (SMEWW 3030 E)' },
        { id: 63 , sampleMethodId: 78 , name: 'SMEWW 3113  (SMEWW 3030 K/ US EPA 3015)SMEWW 3113, (SMEWW 3030 K/ US EPA 3015), SMEWW 3113 (SMEWW 3030 K/ US EPA 3015)' },
        { id: 64 , sampleMethodId: 78 , name: 'SMEWW 3113 (SMEWW 3030 E)' },
        { id: 65 , sampleMethodId: 79 , name: 'SMEWW 3113  (SMEWW 3030 K/ US EPA 3015)' },
        { id: 66 , sampleMethodId: 79 , name: 'SMEWW 3113 (SMEWW 3030 E)' },
        { id: 67 , sampleMethodId: 80 , name: 'SMEWW 3113  (SMEWW 3030 K/ US EPA 3015)' },
        { id: 68 , sampleMethodId: 80 , name: 'SMEWW 3113 (SMEWW 3030 E)' },
        { id: 69 , sampleMethodId: 81 , name: 'SMEWW 9223 B' },
        { id: 70 , sampleMethodId: 82 , name: 'US EPA 5021/ US EPA 8021' },
        { id: 71 , sampleMethodId: 83 , name: 'US EPA 5021/ US EPA 8021' },
        { id: 72 , sampleMethodId: 84 , name: 'SMEWW 3111 C' },
        { id: 73 , sampleMethodId: 85 , name: 'SMEWW 3111 C' },
        { id: 74 , sampleMethodId: 86 , name: 'SMEWW 3030 B; SMEWW 3111 C' },
        { id: 75 , sampleMethodId: 87 , name: 'SMEWW 3111 C' },
        { id: 76 , sampleMethodId: 88 , name: 'SMEWW 3111 C' },
        { id: 77 , sampleMethodId: 89 , name: 'SMEWW 3111 C' },
        { id: 78 , sampleMethodId: 90 , name: 'SMEWW 3111 C' },
        { id: 79 , sampleMethodId: 91 , name: 'SMEWW 3111 C' },
        { id: 80 , sampleMethodId: 92 , name: 'SMEWW 3111 E' },
        { id: 81 , sampleMethodId: 94 , name: 'SMEWW 6630 B/ SMEWW 6630 C/ US EPA 8081' },
        { id: 82 , sampleMethodId: 95 , name: 'SMEWW 6630 B / SMEWW 6630 C / US EPA 8082' },
        { id: 83 , sampleMethodId: 96 , name: 'US EPA 8141' },
        { id: 84 , sampleMethodId: 97 , name: 'SMEWW 6410 B / US EPA 8270' },
        { id: 85 , sampleMethodId: 98 , name: 'SMEWW 6410 B; USEPA 8270' },
        { id: 86 , sampleMethodId: 99 , name: 'SMEWW 6410 B / US EPA 8270' },
        { id: 87 , sampleMethodId: 100 , name: 'SMEWW 6420 B/ US EPA 8041' },
        { id: 88 , sampleMethodId: 105 , name: 'SMEWW 6440 B / US EPA 8100' },
        { id: 89 , sampleMethodId: 106 , name: 'SMEWW 6410 B / US EPA 8270' },
        { id: 90 , sampleMethodId: 107 , name: 'SMEWW 6420 C/ US EPA 8270' },
        { id: 91 , sampleMethodId: 114 , name: 'SMEWW 2540 D' },
        { id: 92 , sampleMethodId: 115 , name: 'SMEWW 2540 C' },
        { id: 93 , sampleMethodId: 116 , name: 'SMEWW 6440 B / US EPA 8310' },
        { id: 94 , sampleMethodId: 143 , name: 'SMEWW 2540 F' },
        { id: 96 , sampleMethodId: 155 , name: 'SMEWW 3120 (SMEWW 3030 F/ USEPA 3010)' },
        { id: 98 , sampleMethodId: 156 , name: 'SMEWW 3120 (SMEWW 3030 F/ USEPA 3010)' },
        { id: 100 , sampleMethodId: 157 , name: 'SMEWW 3120 (SMEWW 3030 F/ USEPA 3010)' },
        { id: 101 , sampleMethodId: 158 , name: 'SMEWW 3120  (SMEWW 3030 K / USEPA 3015)' },
        { id: 103 , sampleMethodId: 159 , name: 'SMEWW 3120 (SMEWW 3030 F/ USEPA 3010)SMEWW 3120, (SMEWW 3030 F/ USEPA 3010)' },
        { id: 104 , sampleMethodId: 160 , name: 'SMEWW 3120 (SMEWW 3030 F/ USEPA 3010)' },
        { id: 109 , sampleMethodId: 154 , name: 'SMEWW 3120 (SMEWW 3030 F/ USEPA 3010)' },
        { id: 110 , sampleMethodId: 161 , name: 'SMEWW 3120 (SMEWW 3030 F/ USEPA 3010)' },
        { id: 112 , sampleMethodId: 162 , name: 'SMEWW 3120 (SMEWW 3030 F/ USEPA 3010)' },
        { id: 114 , sampleMethodId: 163 , name: 'SMEWW 3120 (SMEWW 3030 F/ USEPA 3010)' },
        { id: 116 , sampleMethodId: 164 , name: 'SMEWW 3125  (SMEWW 3030 K / USEPA 3015)' },
        { id: 119 , sampleMethodId: 165 , name: 'SMEWW 3125 (SMEWW 3030 K / USEPA 3015), SMEWW 3125 (SMEWW 3030 K / USEPA 3015) ' },
        { id: 120 , sampleMethodId: 166 , name: 'SMEWW 3125 (SMEWW3030 E)' },
        { id: 122 , sampleMethodId: 167 , name: 'SMEWW 3125 (SMEWW3030 E)' },
        { id: 124 , sampleMethodId: 168 , name: 'SMEWW 3125 (SMEWW3030 E)' },
        { id: 126 , sampleMethodId: 169 , name: 'SMEWW 3125 (SMEWW3030 E)' },
        { id: 128 , sampleMethodId: 170 , name: 'SMEWW 3125 (SMEWW3030 E)' },
        { id: 130 , sampleMethodId: 171 , name: 'SMEWW 3125 (SMEWW 3030 K / USEPA 3015A)' },
        { id: 131 , sampleMethodId: 172 , name: 'SMEWW 3120  (SMEWW 3030 K / USEPA 3015)' },
        { id: 132 , sampleMethodId: 173 , name: 'SMEWW 3120  (SMEWW 3030 K / USEPA 3015)' },
        { id: 133 , sampleMethodId: 174 , name: 'SMEWW 3120  (SMEWW 3030 K / USEPA 3015)' },
        { id: 134 , sampleMethodId: 175 , name: 'SMEWW 3120  (SMEWW 3030 K / USEPA 3015)' },
        { id: 135 , sampleMethodId: 176 , name: 'SMEWW 3120  (SMEWW 3030 K / USEPA 3015)' },
        { id: 136 , sampleMethodId: 177 , name: 'SMEWW 3120  (SMEWW 3030 K / USEPA 3015)' },
        { id: 137 , sampleMethodId: 178 , name: 'SMEWW 3120  (SMEWW 3030 K / USEPA 3015)' },
        { id: 138 , sampleMethodId: 179 , name: 'SMEWW 3120  (SMEWW 3030 K / USEPA 3015)' },
        { id: 139 , sampleMethodId: 180 , name: 'SMEWW 3125 (SMEWW3030 E)' },
        { id: 140 , sampleMethodId: 181 , name: 'SMEWW 3125 (SMEWW3030 E)' },
        { id: 141 , sampleMethodId: 182 , name: 'SMEWW 3125 (SMEWW 3030 K / USEPA 3015A)' },
        { id: 142 , sampleMethodId: 183 , name: 'SMEWW 3125 (SMEWW 3030 K / USEPA 3015A)' },
        { id: 143 , sampleMethodId: 184 , name: 'SMEWW 3125 (SMEWW 3030 K / USEPA 3015A)' },
        { id: 144 , sampleMethodId: 185 , name: 'SMEWW 3125 (SMEWW 3030 K / USEPA 3015A)' },
        { id: 145 , sampleMethodId: 186 , name: 'SMEWW 3125 (SMEWW3030 E)' },
        { id: 146 , sampleMethodId: 187 , name: 'SMEWW 3125 (SMEWW 3030 K / USEPA 3015A)' },
        { id: 147 , sampleMethodId: 188 , name: 'SMEWW 3125 (SMEWW3030 E)' },
        { id: 148 , sampleMethodId: 189 , name: 'SMEWW 3125 (SMEWW 3030 K / USEPA 3015A)' },
        { id: 149 , sampleMethodId: 190 , name: 'SMEWW 3125 (SMEWW3030 E)' },
        { id: 150 , sampleMethodId: 191 , name: 'SMEWW 3125 (SMEWW 3030 K / USEPA 3015A)' },
        { id: 151 , sampleMethodId: 192 , name: 'SMEWW 3125 (SMEWW3030 E)' },
        { id: 152 , sampleMethodId: 193 , name: 'SMEWW 3125 (SMEWW 3030 K / USEPA 3015A)' },
        { id: 153 , sampleMethodId: 194 , name: 'SMEWW 3125 (SMEWW3030 E)' },
        { id: 154 , sampleMethodId: 195 , name: 'SMEWW 3125 (SMEWW 3030 K / USEPA 3015A)' },
        { id: 155 , sampleMethodId: 196 , name: 'SMEWW 3120  (SMEWW 3030 K / USEPA 3015)' },
        { id: 156 , sampleMethodId: 197 , name: 'SMEWW 3120 (SMEWW 3030 F/ USEPA 3010)' },
        { id: 157 , sampleMethodId: 198 , name: 'SMEWW 3120  (SMEWW 3030 K / USEPA 3015)' },
        { id: 158 , sampleMethodId: 199 , name: 'SMEWW 3120 (SMEWW 3030 F/ USEPA 3010)' },
        { id: 159 , sampleMethodId: 200 , name: 'SMEWW  3120 (SMEWW 3030 F/ US EPA 3010)' },
        { id: 160 , sampleMethodId: 201 , name: 'SMEWW  3120  (SMEWW 3030 K / US EPA 3015)' },
        { id: 161 , sampleMethodId: 202 , name: 'SMEWW  4500-O E' },
        { id: 162 , sampleMethodId: 203 , name: 'SMEWW  4500-O C' },
        { id: 163 , sampleMethodId: 204 , name: 'SMEWW  4500-O F' },
        { id: 164 , sampleMethodId: 205 , name: 'SMEWW  4500-O D' },
        { id: 165 , sampleMethodId: 206 , name: 'SMEWW 4110 B' },
        { id: 166 , sampleMethodId: 207 , name: 'SMEWW 4110 B' },
        { id: 167 , sampleMethodId: 208 , name: 'SMEWW 4110 B' },
        { id: 168 , sampleMethodId: 209 , name: 'SMEWW 4110 B' },
        { id: 169 , sampleMethodId: 211 , name: 'SMEWW 4500-F⁻ C' },
        { id: 170 , sampleMethodId: 212 , name: 'SMEWW 2550 B' },
        { id: 171 , sampleMethodId: 213 , name: 'SMEWW 5520 B' },
        { id: 172 , sampleMethodId: 214 , name: 'SMEWW 3114 B' },
        { id: 173 , sampleMethodId: 216 , name: 'SMEWW 3114 B' },
        { id: 174 , sampleMethodId: 217 , name: 'SMEWW  4500-O G' },
        { id: 175 , sampleMethodId: 220 , name: 'SMEWW 9221 E' },
        { id: 176 , sampleMethodId: 221 , name: 'SMEWW 9221 B' },
        { id: 177 , sampleMethodId: 224 , name: 'SMEWW 4500-NO₃ ⁻D / US EPA 9210' },
        { id: 178 , sampleMethodId: 226 , name: 'SMEWW 5220 B' },
        { id: 179 , sampleMethodId: 228 , name: 'SMEWW 4500- Cl⁻ D' },
        { id: 180 , sampleMethodId: 229 , name: 'SMEWW 6200 C / US EPA 8021' },
        { id: 181 , sampleMethodId: 230 , name: 'SMEWW 6200 C / US EPA 8021' },
        { id: 182 , sampleMethodId: 231 , name: 'SMEWW 6200 B / US EPA 8260' },
        { id: 183 , sampleMethodId: 232 , name: 'SMEWW 6200 B / US EPA 8260' },
        { id: 184 , sampleMethodId: 233 , name: 'SMEWW 5520 G' },
        { id: 185 , sampleMethodId: 235 , name: 'SMEWW 4500-F- D' },
        { id: 186 , sampleMethodId: 236 , name: 'SMEWW 4500-P D' },
        { id: 187 , sampleMethodId: 238 , name: 'SMEWW 4500-SO E₄²⁻ E' },
        { id: 188 , sampleMethodId: 241 , name: 'SMEWW 4500-P C' },
        { id: 189 , sampleMethodId: 242 , name: 'SMEWW 2120 B' },
        { id: 190 , sampleMethodId: 243 , name: 'SMEWW 2120 B' },
        { id: 192 , sampleMethodId: 245 , name: 'SMEWW 5530 C' },
        { id: 193 , sampleMethodId: 255 , name: 'SMEWW 3111B / SMEWW 3030 F' },
        { id: 194 , sampleMethodId: 256 , name: 'SMEWW 3120 / SMEWW 3030 F' },
        { id: 195 , sampleMethodId: 259 , name: 'SMEWW 9221 B' },
    ];

    // Insert data into SampleType
    await prisma.sampleType.createMany({
        data: sampleTypes,
        skipDuplicates: true, // Avoid duplicate insertion
    });

    console.log('SampleType data seeded successfully.');

    // Insert data into Parameter
    await prisma.parameter.createMany({
        data: parameters,
        skipDuplicates: true, // Avoid duplicate insertion
    });

    console.log('Parameter data seeded successfully.');

    // Insert data into SampleMethod
    await prisma.sampleMethod.createMany({
        data: sampleMethods,
        skipDuplicates: true, // Avoid duplicate insertion
    });

    console.log('SampleMethod data seeded successfully.');

    // Insert data into SampleReference
    await prisma.sampleReference.createMany({
        data: sampleReferences,
        skipDuplicates: true, // Avoid duplicate insertion
    });

    console.log('SampleReference data seeded successfully.');

}

main()
    .catch((error) => {
        console.error('Error seeding data:', error);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
